# Generated by Django 5.2 on 2025-04-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='created_at',
            new_name='posted_at',
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='نامشخص', max_length=100),
            preserve_default=False,
        ),
    ]
