# Generated by Django 5.2 on 2025-05-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_created_at_job_posted_at_job_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('resume', models.FileField(upload_to='resumes/', verbose_name='رزومه')),
                ('cover_letter', models.TextField(verbose_name='متن درخواست')),
            ],
        ),
    ]
