# Generated by Django 5.2 on 2025-05-10 01:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobapplication_submitted_at_delete_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='فایل رزومه'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_text',
            field=models.TextField(blank=True, verbose_name='توضیحات رزومه'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True, verbose_name='متن درخواست'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ارسال'),
        ),
    ]
