services:
  - type: web
    name: job_sit
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn jobboard.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jobsit
          property: connectionString
      - key: DJANGO_SECRET_KEY
        value: 0bbd1fbe1523d6f62876bd5dbdbe8fe
